chore: only format and lint the staged files in the pre-commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,43 +1,53 @@
 #!/bin/bash
 exec </dev/tty
 cd "$(git rev-parse --show-toplevel)"
+
 staged_files=$(git diff --cached --name-only)
+staged_frontend=$(echo "$staged_files" | grep -E '^client/' | sed 's|^client/||' || true)
+staged_backend=$(echo "$staged_files" | grep -E '^server/' | sed 's|^server/||' || true)
+
 echo "[pre-commit] Running pre-commit hook"
-echo "[pre-commit] Checking frontend code"
-cd client
-linter_output=$(npx eslint .)
-if [ -n "$linter_output" ]; then
-  echo "[pre-commit] ESLint found issues below:"
-  echo "$linter_output"
-  read -p "[pre-commit] Would you like to abort the commit? (y/N) " answer
-  answer=${answer:-N}
-  if [[ "$answer" =~ ^[Yy]$ ]]; then
-    echo "[pre-commit] Aborting"
-    exit 1
+
+if [ -n "$staged_frontend" ]; then
+  echo "[pre-commit] Checking frontend code"
+  cd client
+  linter_output=$(npx eslint ${staged_frontend[@]})
+  if [ -n "$linter_output" ]; then
+    echo "[pre-commit] ESLint found issues below:"
+    echo "$linter_output"
+    read -p "[pre-commit] Would you like to abort the commit? (y/N) " answer
+    answer=${answer:-N}
+    if [[ "$answer" =~ ^[Yy]$ ]]; then
+      echo "[pre-commit] Aborting"
+      exit 1
+    fi
   fi
-fi
-echo "[pre-commit] Formatting frontend code"
-npx eslint . --fix --quiet
-echo "[pre-commit] Checking backend code"
-cd ../server
-linter_output=$(uv run ruff check --fix --quiet)
-if [ -n "$linter_output" ]; then
-  echo "[pre-commit] Ruff found issues below:"
-  echo "$linter_output"
-  read -p "[pre-commit] Would you like to abort the commit? (y/N) " answer
-  answer=${answer:-N}
-  if [[ "$answer" =~ ^[Yy]$ ]]; then
-    echo "[pre-commit] Aborting"
-    exit 1
-  fi
-fi
-echo "[pre-commit] Formatting backend code"
-uv run ruff format
-cd ..
-if [ -z "$staged_files" ]; then
-  echo "[pre-commit] No files staged for commit"
-else
+  echo "[pre-commit] Formatting frontend code"
+  npx eslint ${staged_frontend[@]} --fix --quiet
   echo "[pre-commit] Staging formatted files"
-  git add ${staged_files[@]}
+  git add ${staged_frontend[@]}
+  cd ..
 fi
+
+if [ -n "$staged_backend" ]; then
+  echo "[pre-commit] Checking backend code"
+  cd server
+  linter_output=$(uv run ruff check ${staged_backend[@]} --fix --quiet)
+  if [ -n "$linter_output" ]; then
+    echo "[pre-commit] Ruff found issues below:"
+    echo "$linter_output"
+    read -p "[pre-commit] Would you like to abort the commit? (y/N) " answer
+    answer=${answer:-N}
+    if [[ "$answer" =~ ^[Yy]$ ]]; then
+      echo "[pre-commit] Aborting"
+      exit 1
+    fi
+  fi
+  echo "[pre-commit] Formatting backend code"
+  uv run ruff format ${staged_backend[@]}
+  echo "[pre-commit] Staging formatted files"
+  git add ${staged_backend[@]}
+  cd ..
+fi
+
 echo "[pre-commit] Done"
