feat: add confirmation when found issues in frontend

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,10 +1,23 @@
 #!/bin/bash
+exec < /dev/tty
 cd "$(git rev-parse --show-toplevel)"
 staged_files=$(git diff --cached --name-only)
 echo "[pre-commit] Running pre-commit hook"
-echo "[pre-commit] Formatting frontend code"
+echo "[pre-commit] Checking frontend code"
 cd client
-npx eslint --fix src vite.config.js eslint.config.js
+linter_output=$(npx eslint)
+if [ -n "$linter_output" ]; then
+  echo "[pre-commit] ESLint found issues below:"
+  echo "$linter_output"
+  read -p "[pre-commit] Would you like to abort the commit? (y/N) " answer
+  answer=${answer:-N}
+  if [[ "$answer" =~ ^[Yy]$ ]]; then
+    echo "[pre-commit] Aborting"
+    exit 1
+  fi
+fi
+echo "[pre-commit] Formatting frontend code"
+npx eslint --fix --quiet src vite.config.js eslint.config.js
 prettier src vite.config.js eslint.config.js --print-width 100 -w
 echo "[pre-commit] Formatting backend code"
 cd ../server
